### ISSUE TITLE
Bracket expressions should support another Bracket or Lookup

### ISSUE THREAD

**Issue by ccummings** [canjs/can-stache#109]
These throw errors at the moment:

`{{device[prop].anotherProp}}`
`{{device[prop][anotherProp]}}`

**Comment by phillipskevin** [comment]
`{{device[prop][anotherProp]}}` is working, but `{{device[prop].anotherProp}}` is not working

**Comment by phillipskevin** [comment]
Supporting `{{device[prop].anotherProp}}` would require larger changes to the tokenizer in order to differentiate `{{device[prop].anotherProp}}` from `{{device[prop] anotherProp}}` because there is no way to use a regular expression to match a space only when it follows a `]`.

Since you can do `{{device[prop]['anotherProp']}}` to achieve the same thing I don't think this is urgent to fix right now. I'll separate this out into another issue.
