### ISSUE TITLE
Remove special syntax in production

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache#158]
Question: would it be possible for `can-stache` (or `can-stache-bindings`?) to remove (or not add) the binding syntax from the DOM it produces?

Here’s an example of some [SSR’d HTML on PMO](http://www.place-my-order.com/restaurants): 
```html
<select {($value)}="city" value disabled>
  <option value>Choose a city</option>
</select>
```

Would it be possible for `{($value)}="city"` not to be added to the `select`? Is it used by anything after it’s in the DOM?

I value seeing those attributes when I’m developing, but if they’re not required in production, the SSR’d HTML would be a little bit smaller and [more valid](https://github.com/donejs/donejs/issues/655#issuecomment-278145395).

**Comment by justinbmeyer** [comment]
These are "mostly" needed.  The reason is we support dynamic attributes.  So something like `{prop}="value"` actually can be changed via `.setAttribute()` (in browsers that support these types of attributes).  

It would probably involve breaking change or a special mode.

I can imagine these attributes becoming more important as we get closer to actual custom elements.

If a user does something like:

`.setAttribute("{prop}", "value")` ... and the browser supports it ... would we want to setup a binding if we can?
