### ISSUE TITLE
missmatched tags warnings incorrect

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-stache#214]
Missmatched tag warnings were introduced in #171, but are incorrect in some cases.

```javascript
{{#games.getAvailableCourts(selectedRound)}}
   <option value="{{.}}">{{.}}</option>
{{/games.getAvailableCourts}}
```

produces `unexpected closing tag {{/games.getAvailableCourts}} expected {{/ames@getAvailableCourts}}`

**Comment by bmomberger-bitovi** [comment]
Notes on this issue:

When parsing the Stache into an AST, a key lookup token token like `games.getAvailableCourts` is converted into an "at" expression `games@getAvailableCourts` when the parser finds it heading up an M-expression for Call syntax, using the stack function `convertToAtLookup()`.  This makes sense, because we need the final element in the lookup to be preserved as a callable function. 

If there weren't a dot in the lookup expression, an @ would be prepended to the token.  This is what `Call.prototype.closingTag()` expects when parsing the key lookup back into its original token (the original expression text is not preserved after converting to an "at" lookup), but this expectation is not correct for all possible converted lookups.

So one of two possible paths could be taken here:

1) preserve the original key in the Lookup expression by using another property (i.e. `originalKey`), and use that if it exists in the comparison in `makeRendererAndUpdateSection()`;

2) Loosen the comparison in `makeRendererAndUpdateSection()` to ignore discrepancies between `.` and `@` in the same position;

3) change the tag returned from `Call.prototype.closingTag()` into a regex (NB: I don't recommend this; this is probably much slower than the other solutions)

@christopherjbaker ?

**Comment by christopherjbaker** [comment]
After reading your initial description, my first thought was your number 2 above. If the original key is available, 1 might be a less temperamental option, however.

In looking over the code changes before, I am also noticing that [this logic](https://github.com/canjs/can-stache/blob/master/src/expression.js#L276-L278) needs to be changed. It was set up to trim the leading `@` (and I had not noticed instances where it was not leading). I think 2 could be accomplished by just changing this to trim a leading `@` and swap out any inner ones for `.` (with a similar change [here](https://github.com/canjs/can-stache/blob/master/src/expression.js#L472-L474)).

**Comment by bmomberger-bitovi** [comment]
Don't worry about fixing it, as I am working on it now, but I wanted your insight from having worked on it before
