### ISSUE TITLE
promise.isResolved and promise.isPending in getter called repeatedly

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-stache#236]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

[demo repo](https://github.com/roemhildtg/canjs-promise-show-bug/blob/master/index.html)

The issue occurs in stache templates with `{{promise.isPending}}` or `isResolved` where the promise is in a getter like:

``` 
DefineMap.extend({
    promise: {
        get(){
            return new Promise(.....);
       }
    }
```

It doesn't occur immediately, but if the block that has the `isPending` is toggled and shown again, calls to the getter are repeated. 

__Expected results:__

The getter should only be called once, unless data in the promise getter changes, which in this case it's not.

__Actual results:__

The promise getter is called repeatedly until the end of time.

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  |  can-stache-3.2.0
| Browser                    |  Chrome
| Operating system    |  Windows

**Comment by roemhildtg** [comment]
Updated with jsbin:

http://jsbin.com/yupizulija/edit?html,js,console,output

Could be related to https://github.com/canjs/can-stache/issues/239 since it only happens when dom element is removed and inserted again.

**Comment by justinbmeyer** [comment]
I don't think this is a bug. Getters are only cached when bound. When the element is removed, all bindings are also removed. When the element is inserted again, the getter needs to be run again. 

Can you use 'value' instead of a getter. 

The other thing that might work are "weak bindings". This is an idea that we will bind properties of a VM if any of its other props are bound.

**Comment by roemhildtg** [comment]
The getter runs again, yes, but it continues to run every second after it is inserted again. The console gets logged every time the promise resolves.

**Comment by justinbmeyer** [comment]
Oh, @phillipskevin I think our fixes will fix this.  Can you try this with the changes to `can-observation` around:

```
if (!this.handlers) {
                this.handlers = [];
                if (this.compute.updater) {
                    console.warn('can-observation bound to with an existing handler');
                }
                this.compute.updater = callHandlers.bind(this);
                this.start();
            }
            this.handlers.push(handler);
```

**Comment by justinbmeyer** [comment]
@roemhildtg please try upgrading the following:

https://github.com/canjs/can-view-scope/releases/tag/v3.3.1
https://github.com/canjs/can-observation/releases/tag/v3.3.2

Let us know if this fixes it ... it should because I can see the same problem in your JSBin.  I'll try to get a release out tomorrow.

**Comment by roemhildtg** [comment]
Yep this is fixed.
