### ISSUE TITLE
Suggestion: add line number or file name of unmatched tags

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-stache#252]
__Description:__

can-stache prints out lines like `log.js:102 WARN: unexpected closing tag </div>` which could be super helpful _if_ there was some reference to where that tag was. I think that if stache gave some sort of indication as to where that div was, like the component name or template name it would help track down the problematic template.

**Comment by roemhildtg** [comment]
Related to https://github.com/canjs/can-stache/issues/149

**Comment by christopherjbaker** [comment]
After some digging, I think I could track line numbers during parsing in [can-view-parser[(https://github.com/canjs/can-view-parser/blob/master/can-view-parser.js#L167). They would need to be available in the `handler.<method>()` calls in order to output them; at this point, those only contain very simple data (`handler.start(tagName, unary);`), so the line number would need to be an extra argument I think. Thoughts, @phillipskevin?

**Comment by phillipskevin** [comment]
Let's touch base on this tomorrow @christopherjbaker.

**Comment by justinbmeyer** [comment]
Maybe wait for can-parse?
