### ISSUE TITLE
Deprecate {{#each x as KEY}} in favor of {{#each x item=value num=index}}

### ISSUE THREAD

**Issue by James0x57** [canjs/can-stache#300]
The direction we're going with for aliasing #with scope here:
https://github.com/canjs/can-stache/issues/274

Says that instead of using 'as', we should do handlebars-esque multi variable assignment using a hash:
`{{#with first=person.first last=anotherPerson.last}}`
meaning these are identical:
`{{#with person}}` === `{{#with this=person}}`

-----
So the goal is:

- [ ] to support this: `{{#each items item=value num=index}}`
- [ ] and deprecate `{{#each items as KEY}}`

There is also a discussion about changing each-block aliasing here:
https://github.com/canjs/can-stache/issues/289

**Comment by James0x57** [comment]
Note: this is under discussion, not as anything set in stone

**Comment by phillipskevin** [comment]
I don't like that you would have to remember `value` and `index` are the correct keys. 

It seems like this just adds things you have to remember without much benefit.

Why not just `{{#each items item num}}` or maybe `{{#each items with item num}}` or `{{#each items #with item num}}`.

**Comment by phillipskevin** [comment]
After talking about this, I think `value`/`index` as keywords for `{{#each}}` loops with arrays is fine. We will also need to reserve `key` for `value`/`key` for looping over objects.

**Comment by Macrofig** [comment]
I'm going through the [3.11 tasks](https://github.com/canjs/canjs/issues/3495) and without any context, this issue seems large; it seems to need some breaking down. So far, I can see,

- Add deprecation warning when using `{{#each VALUE as KEY}}`
- Create documentation for new API; blog post?
- Update tests, update code (As clear as I can be without looking at can-stache)

Of course, this is all after the discussion leads to a decision on the api. Anyway, just want to leave a note that this needs to be broken down before points are assigned.
