### ISSUE TITLE
Two way binding with nested properties doesn't update from parent to child

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-stache#408]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

If I set up a template to bind to a nested property on a component's view model, the parent scope is updated, but if the parent scope changes, the component view model nested prop doesn't get updated, instead it gets a new property `obj.propName`.

https://jsbin.com/furiquqepo/1/edit?html,js,output

__Steps to reproduce:__

```html
<script id="app-template" type="text/stache">

  <home-page textData.textValue:bind="textString" />
  
  <input value:bind="textString"/>

</script>
  
<script id="home-template" type="text/stache">
<h1>Home Page</h1>
<input value:bind="textData.textValue" />

</script>
```

__Expected results:__

The component nested property should be updated, rather than getting a new one.

__Actual results:__

A new property with a . is created on the component vm. 

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 3.14.2
| Browser                    |  Chrome
| Operating system    |  Windows

**Comment by justinbmeyer** [comment]
Thanks for reporting.  Checking it out.

**Comment by justinbmeyer** [comment]
Binding with `.` isn't currently supported.  We could add it.  As a workaround, you should be able to do something like:

```js
get textDataTextValue(){
  return this.textData.textValue
},
set textDataTextValue(newVal){
  this.textData.textValue = newVal
}
```

```html
 <home-page textDataTextValue:bind="textString" />
```


To fix this, `can-stache-bindings` would need to use `can-stache-key`'s `.set` (or `.write`) around [here](https://github.com/canjs/can-stache-bindings/blob/8e230be49b53d98bec6ea378e39d183cb7bf3197/can-stache-bindings.js#L787) instead of basically duplicating the logic in `can-stache-bindings`.

```js
observeReader.write(viewModel, keysToRead, value);
```

We are already using it to read here to read the value from the view model (`can-stache-key` is called `observeReader`):

```js
		var observation = new Observation(function() {
			var viewModel = bindingData.getViewModel();
			return observeReader.read(viewModel, keysToRead, {}).value;
		});
```

**Comment by justinbmeyer** [comment]
Here is an updated version of this problem: https://codepen.io/justinbmeyer/pen/eoPqEX?editors=1011

**Comment by Mattchewone** [comment]
This was fixed in `can-stache-bindings` - https://github.com/canjs/can-stache-bindings/releases/tag/v4.10.2
