### ISSUE TITLE
major: the default helper should be able to be called as a function

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#435]
As shown on https://canjs.github.io/next/doc/can-stache.helpers.default.html, this should work:

```
{{#switch(user.type)}}
    ...
    {{#default()}}
        ...
    {{/default}}
{{/switch}}
```

**Comment by matthewp** [comment]
Maybe we should have some sort of keyword identifier? I'm not sure what you call these types of things, but it's function-like keywords that are treated like functions, but `()` are not required. In JavaScript thing `typeof`, `new`, etc. Should we have something like that in stache? So that default would work, without the need for special-casing? cc @justinbmeyer

**Comment by phillipskevin** [comment]
I don't know if it's really special-casing. It's basically a "value-like" function like the old `can-compute`. I'm planning to use [can-simple-observable/make-compute](https://github.com/canjs/can-simple-observable/blob/major/make-compute/make-compute.js).

**Comment by phillipskevin** [comment]
Or maybe just a function with a `getValue` symbol, since I'd have to add `can-simple-observable` as a dependency of `can-stache` and it doesn't really need everything that `make-compute` does.

**Comment by phillipskevin** [comment]
Maybe these solutions won't work... still trying.

**Comment by matthewp** [comment]
Symbol idea sounds solid to me.

**Comment by frank-dspeed** [comment]
@phillipskevin I think this can be closed as already merged.
