### ISSUE TITLE
debugger should work without ()

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache#469]
This should work to all the debugger helper so that it works like every other built-in helper:
```
{{debugger}}
```

To make this work, we'll probably need to do the same thing that we do with `{{default}}`: https://github.com/canjs/can-stache/blob/bcb5b78623276d95c582cce83d14c51d84707114/helpers/core.js#L245-L256

**Comment by christopherjbaker** [comment]
I added this to the debuggerHelper

```canReflect.assignSymbols(debuggerHelper, {
	"can.isValueLike": true,
	"can.isFunctionLike": false,
	"can.getValue": function() {
		return this();
	}
});```

however this is resulting it in being called with no arguments (since it has `this()` and the getValue function also has no arguments), so the `get` function will not work.

Also, in addition to the two logs that the debugger outputs (`Use `get(<path>)` to debug this template` and `Forgotten {{debugger}} helper`), it is also outputting `can-stache/expressions/lookup.js: Unable to find key "debugger".` I can fix this by returning a truthy value, but I think this will output to the page, which I think is undesirable.

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-view-scope #153](https://github.com/canjs/can-view-scope/issues/153) via [**ZenHub**](https://www.zenhub.com/)

**Comment by phillipskevin** [comment]
Going to add a test here and bump the can-view-scope dependency to make this work.
