### ISSUE TITLE
Migrating from can-stache@4.3.4 -> can-stache 4.4.0 and can-stache 4.5.1

### ISSUE THREAD

**Issue by DaveO-Home** [canjs/can-stache#533]
__How often can you reproduce it?__ 

- [x ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__ 
After migrating from can-stache@4.3.4 -> can-stache 4.4.0
WARN: '1: Unable to find key "selectedJobType".
', '
when running the app.

-> can-stache 4.5.1 (also - can-util@3.11.6)
ERROR: Error: You can't have two versions of can-globals, check your dependencies

Template:
<span>Select Job Type: <jobtype-selector to="jobtype-selector" /></span><br/>

Model:
tag: "jobtype-selector",
view: Stache("\<select  class='jobtype-selector' value:bind='selectedJobType'>" +
         this.getOptions(osKeys, values) +
         "\</select>"),......

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible
You can use "github.com/DaveO-Home/embedded-acceptance-tests" to reproduce
2. Detail the exact steps taken to produce the problem
npm install can-stache@4.4.0
npm install can-stache@4.5.1
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__  Expected the application to function - it fails at startup.

__Actual results:__ Non-functioning app

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 
| Browser                    |  Chrome 66/Firefox 60
| Operating system    | Fedora 28

**Comment by chasenlehara** [comment]
__Short answer:__ installing both the `can` package and the individual packages (like can-stache) isn’t supported. If you *really* wanted to get the most recent of can-stache *right now*, we can talk through some options, but otherwise I’d wait until can@4.3 is out (sometime in the next couple weeks?).

__Long answer:__

The `can` package pins all its `can-*` dependencies to specific versions, so when you install a specific version of `can`, it has an exact set of dependencies that have been fully vetted/tested.

Some packages, like `can-globals`, are stateful; if there are multiple versions of the package running in an app, then unexpected, hard-to-debug issues will probably occur. This is why we throw an error if we detect that multiple versions of these stateful packages are being included on the same page.

`can-stache@4.5.0` depends on a newer version of `can-globals` than what’s in `can@4.2.0`, so after you install both, you’ll notice that `npm ls can-globals` shows multiple versions of `can-globals` installed… and because that package is stateful, CanJS tries to save you from some subtle bug nightmare that could occur.

To reiterate what’s in the short answer… unless you need to install a newer version of `can-stache` right now, I’d wait until the `can` package has been updated.

Alternatively, you could switch from using `can` to using the individual `can-*` packages. This can be automated with [can-migrate](https://canjs.com/doc/guides/upgrade/using-codemods.html); I think by running something like this on the command-line in your project:

```
npm i -g can-migrate@2
can-migrate '**/*.js' --can-version 3 --apply
```

Sorry for the lengthy, probably confusing, reply. I’m going to close this for now but I’m happy to answer any questions about it. 🙂

**Comment by DaveO-Home** [comment]
@chasenlehara - Ya, I saw that can-migrate package, but didn't think it useful since I'm already @4.3. I use the npm configuration,  so steal want's each module in package.json, it would be nice to just have "can" in package.json.  But I have started to use "package-lock.json" so a vanilla "npm install" should always work. Also, when I do "npm outdated" as suggested in the migration guide, I get can-* modules coded in red, suggesting a needed upgrade.  So I think there is still a disconnect between npm and can-* upgrading. Based on your explanation, I'm still not sure when and what to upgrade. But thanks for the verbiage, it was helpful....  Also, I'm not sure how I got both "can" and can-* modules together, I will try to remove "can".

**Comment by chasenlehara** [comment]
Since you have `can-stache` and `can-util` installed as a dependency of your project, I think npm is right to show that those are outdated… it’s just confusing because you can’t update without breaking your `can` install.

Right now, I would recommend removing `can` from your project and installing just the packages you need. `can-migrate` can help if you have a lot of code to transform from stuff like `require("can/component/")` to `require("can-component")`

**Comment by chasenlehara** [comment]
Ugh, I hate how complicated this is…

I should mention that in CanJS 4, we also support using the `can` package with module loaders/bundlers that have tree-shaking / ES module support. That’s documented in this guide: https://canjs.com/doc/guides/advanced-setup.html

In CanJS 5, the `can/es` module will be the default `can` export, so we’re going to switch our guides over to showing that instead. We’re doing this because we’ve found that newcomers are intimidated by the number of packages and having to install them individually.

We’ll have a (more advanced) guide that covers what we recommend now, which is to use the individual packages directly. This’ll always get you updates faster than what’s available through the main `can` package, which is one reason why you might want to continue using the individual packages in the future.
